name: MT Business Hosting
favicon: null
layout_spectrum: 0.2608531815931201
typography_spectrum: 0.7023275473620743
title: 'Getting you online is fast and easy '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2782d1'
    - '#b89b61'
    - '#171918'
    - '#fcfefd'
    - '#c3cfcc'
  brandStrength: 0.0625
  lightness: 0.25
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
