name: MT Business Hosting
favicon: null
layout_spectrum: 0.2608531815931201
typography_spectrum: 0.7023275473620743
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4981933170929551
  lightness: 0.5157833164557815
  saturation: 0.9427720147650689
  rhythmicContrast: 0.2755372473038733
purpose: []
